# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/balazskokai/android_kernel_samsung_exynos7870
          kernel-branch: h-kernel_permissive
          config: exynos7870-j5y17lte_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: v0.9.5
          android-version: 10
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: true
